import type { BrandWithScores } from "./types";

/**
 * Static seed data ported from the demo site's brands.js.
 * Used as fallback when Supabase has no published reviews yet.
 * Once real reviews flow in, this data gets replaced by DB aggregates.
 */
export const SEED_BRANDS: BrandWithScores[] = [
  { id: "seed-brooks", name: "Brooks", slug: "brooks", domain: "brooksrunning.com", logo_url: null, categories: ["Running"], claimed_by: null, description: "A leading manufacturer of high-performance running footwear, apparel, and accessories, known for its strong commitment to specialty retail partners.", created_at: "", score: 88, dims: [18, 18, 17, 18, 17], review_count: 142, change: "+12", spark: [18, 10, 14, 4] },
  { id: "seed-hoka", name: "Hoka", slug: "hoka", domain: "hoka.com", logo_url: null, categories: ["Running", "Outdoor"], claimed_by: null, description: "A premium running and outdoor footwear brand recognized for maximum cushioning and rapid product innovation.", created_at: "", score: 78, dims: [17, 14, 18, 15, 14], review_count: 38, change: "+18", spark: [20, 16, 12, 6] },
  { id: "seed-patagonia", name: "Patagonia", slug: "patagonia", domain: "patagonia.com", logo_url: null, categories: ["Outdoor", "Surf", "Ski"], claimed_by: null, description: "An outdoor apparel and gear company known for environmental stewardship and lifetime repair commitments.", created_at: "", score: 76, dims: [16, 14, 16, 16, 14], review_count: 31, change: "+9", spark: [20, 18, 16, 10] },
  { id: "seed-nemo", name: "Nemo", slug: "nemo", domain: "nemoequipment.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Designer of innovative outdoor sleeping bags, tents, and camping gear, born from a New Hampshire engineering studio.", created_at: "", score: 75, dims: [15, 15, 16, 15, 14], review_count: 12, change: "-3", spark: [10, 12, 15, 16] },
  { id: "seed-big-agnes", name: "Big Agnes", slug: "big-agnes", domain: "bigagnes.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "A Steamboat Springs-based maker of lightweight tents, sleeping bags, and pads built for backcountry trips.", created_at: "", score: 73, dims: [15, 14, 15, 15, 14], review_count: 14, change: "-1", spark: [10, 12, 14, 15] },
  { id: "seed-yeti", name: "YETI", slug: "yeti", domain: "yeti.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Premium coolers, drinkware, and outdoor lifestyle products engineered for durability and performance.", created_at: "", score: 71, dims: [13, 16, 14, 14, 14], review_count: 22, change: "+2", spark: [12, 10, 14, 11] },
  { id: "seed-black-diamond", name: "Black Diamond", slug: "black-diamond", domain: "blackdiamondequipment.com", logo_url: null, categories: ["Outdoor", "Ski"], claimed_by: null, description: "Climbing, skiing, and mountain sports equipment, designed by climbers in Salt Lake City.", created_at: "", score: 70, dims: [14, 14, 14, 15, 13], review_count: 18, change: "+1", spark: [14, 13, 13, 12] },
  { id: "seed-salomon", name: "Salomon", slug: "salomon", domain: "salomon.com", logo_url: null, categories: ["Running", "Outdoor", "Ski"], claimed_by: null, description: "French maker of trail running, hiking, and ski equipment with a strong heritage in alpine sport.", created_at: "", score: 67, dims: [13, 13, 14, 14, 13], review_count: 16, change: "0", spark: [13, 14, 12, 13] },
  { id: "seed-on", name: "On", slug: "on", domain: "on.com", logo_url: null, categories: ["Running"], claimed_by: null, description: "Swiss running brand known for CloudTec sole technology and rapid growth in performance and lifestyle categories.", created_at: "", score: 65, dims: [14, 12, 14, 13, 12], review_count: 11, change: "+6", spark: [18, 15, 12, 10] },
  { id: "seed-cotopaxi", name: "Cotopaxi", slug: "cotopaxi", domain: "cotopaxi.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Outdoor apparel and gear maker with a benefit corporation model and a focus on humanitarian impact.", created_at: "", score: 62, dims: [12, 13, 12, 13, 12], review_count: 9, change: "+4", spark: [16, 14, 11, 8] },
  { id: "seed-smartwool", name: "Smartwool", slug: "smartwool", domain: "smartwool.com", logo_url: null, categories: ["Outdoor", "Running"], claimed_by: null, description: "Performance merino wool socks and apparel, designed in Steamboat Springs, Colorado.", created_at: "", score: 60, dims: [12, 12, 12, 12, 12], review_count: 10, change: "-2", spark: [12, 14, 13, 15] },
  { id: "seed-arcteryx", name: "Arc'teryx", slug: "arcteryx", domain: "arcteryx.com", logo_url: null, categories: ["Outdoor", "Ski"], claimed_by: null, description: "Vancouver-based technical apparel and equipment company known for premium alpine outerwear.", created_at: "", score: 58, dims: [12, 12, 11, 13, 10], review_count: 13, change: "-5", spark: [8, 12, 16, 20] },
  { id: "seed-keen", name: "KEEN", slug: "keen", domain: "keenfootwear.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "American footwear company best known for hybrid sandal-shoes and an emphasis on toe protection.", created_at: "", score: 56, dims: [11, 11, 12, 12, 10], review_count: 8, change: "+14", spark: [20, 16, 14, 8] },
  { id: "seed-osprey", name: "Osprey", slug: "osprey", domain: "osprey.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Backpack and travel pack specialist, designed in Cortez, Colorado, with a guaranteed-for-life warranty.", created_at: "", score: 55, dims: [11, 11, 11, 12, 10], review_count: 11, change: "-1", spark: [14, 13, 15, 16] },
  { id: "seed-kelty", name: "Kelty", slug: "kelty", domain: "kelty.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "American outdoor brand offering accessible camping gear, packs, and family-friendly outdoor equipment.", created_at: "", score: 52, dims: [10, 11, 10, 11, 10], review_count: 7, change: "+1", spark: [14, 15, 13, 14] },
  { id: "seed-tnf", name: "The North Face", slug: "the-north-face", domain: "thenorthface.com", logo_url: null, categories: ["Outdoor", "Ski"], claimed_by: null, description: "Global outdoor brand offering technical apparel, footwear, and equipment across alpine, run, and lifestyle categories.", created_at: "", score: 48, dims: [7, 11, 9, 12, 9], review_count: 17, change: "-4", spark: [10, 12, 15, 18] },
  { id: "seed-kuhl", name: "Kuhl", slug: "kuhl", domain: "kuhl.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Salt Lake City-based outdoor apparel brand known for durable mountain pants and casual mountain style.", created_at: "", score: 45, dims: [8, 10, 8, 10, 9], review_count: 6, change: "+2", spark: [18, 16, 15, 14] },
  { id: "seed-columbia", name: "Columbia", slug: "columbia", domain: "columbia.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Mass-market outdoor apparel company with a wide range of value-oriented technical clothing and footwear.", created_at: "", score: 42, dims: [7, 10, 7, 10, 8], review_count: 15, change: "-6", spark: [10, 14, 18, 20] },
  { id: "seed-mhw", name: "Mountain Hardwear", slug: "mountain-hardwear", domain: "mountainhardwear.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Technical alpine and climbing apparel and equipment brand, originally spun out of Sierra Designs.", created_at: "", score: 40, dims: [7, 9, 7, 10, 7], review_count: 7, change: "0", spark: [16, 15, 16, 16] },
  { id: "seed-prana", name: "prAna", slug: "prana", domain: "prana.com", logo_url: null, categories: ["Outdoor"], claimed_by: null, description: "Yoga, climbing, and travel apparel brand emphasizing sustainable materials and natural fibers.", created_at: "", score: 38, dims: [6, 8, 7, 9, 8], review_count: 7, change: "-3", spark: [12, 15, 14, 16] },
];
